// ============================================================
// APPLICATION LOGIC
// ============================================================
// Do not edit this file unless you know what you're doing.
// All content lives in js/config.js and js/quotes/*.js
// ============================================================

(function () {
  // ---------- STATE ----------
  // Finnish is the primary/default language.
  const DEFAULT_LANG = 'fi';
  const FALLBACK_LANG = 'en';
  let currentLang = localStorage.getItem('lang') || DEFAULT_LANG;

  // ---------- HELPERS ----------
  const $ = sel => document.querySelector(sel);
  const t = key => (ui[currentLang] && ui[currentLang][key])
                 || ui[DEFAULT_LANG][key]
                 || ui.en[key];
  // pick: use current lang → fallback Finnish → English
  const pick = obj => {
    if (!obj) return "";
    return obj[currentLang] || obj[DEFAULT_LANG] || obj[FALLBACK_LANG] || "";
  };

  // ---------- LANGUAGE BAR ----------
  function setupLangBar() {
    const bar = $('#langBar');
    if (!bar) return;
    bar.querySelectorAll('button').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === currentLang);
    });
  }

  function bindLangBar() {
    const bar = $('#langBar');
    if (!bar) return;
    bar.querySelectorAll('button').forEach(btn => {
      btn.addEventListener('click', () => {
        currentLang = btn.dataset.lang;
        localStorage.setItem('lang', currentLang);
        refresh();
      });
    });
  }

  // ---------- TOP NAV ----------
  // Marks the current page (Home or a specific author) as .active,
  // then scrolls that item into view so it's visible on screen.
  function renderNav() {
    const nav = $('#topNav');
    if (!nav) return;

    const page = document.body.dataset.page;
    let activeId = null;
    if (page === 'author') {
      activeId = new URLSearchParams(location.search).get('id');
    }

    nav.innerHTML =
      `<a href="index.html" class="${page === 'home' ? 'active' : ''}">${t('home')}</a>` +
      AUTHORS.map(a => {
        const cls = (a.id === activeId) ? 'active' : '';
        return `<a href="author.html?id=${a.id}" class="${cls}">${a.name}</a>`;
      }).join('');

    // Scroll the active menu item into the visible area (centered).
    // Uses requestAnimationFrame so it runs after the browser has
    // laid out the new nav items.
    requestAnimationFrame(() => {
      const activeEl = nav.querySelector('a.active');
      if (activeEl) {
        activeEl.scrollIntoView({
          behavior: 'smooth',
          inline: 'center',
          block: 'nearest'
        });
      }
    });
  }

  // ---------- HOME PAGE ----------
  function renderHome() {
    $('#homeTitle').textContent = t('homeTitle');
    $('#homeSub').textContent = t('homeSub');
    const grid = $('#authorsGrid');
    grid.innerHTML = AUTHORS.map(a => `
      <div class="author-card">
        <h3>${a.name}</h3>
        <div class="years">${a.years}</div>
        <a class="btn" href="author.html?id=${a.id}">${t('quotesBtn')}</a>
      </div>
    `).join('');
  }

  // ---------- AUTHOR PAGE ----------
  function getAuthorFromUrl() {
    const params = new URLSearchParams(location.search);
    const id = params.get('id');
    return AUTHORS.find(a => a.id === id);
  }

  function ensureQuotesLoaded(authorId, callback) {
    if (window.QUOTES && window.QUOTES[authorId]) {
      callback();
      return;
    }
    const script = document.createElement('script');
    script.src = `js/quotes/${authorId}.js`;
    script.onload = callback;
    script.onerror = callback;
    document.head.appendChild(script);
  }

  function renderQuotes(author, quotes) {
    const list = $('#quoteList');
    if (!quotes || !quotes.length) {
      list.innerHTML = `<p>${t('noQuotes')}</p>`;
      return;
    }
    list.innerHTML = quotes.map(q => {
      const text = pick(q);
      const src = pick(q.source);
      const langLabel = currentLang.toUpperCase();
      return `
        <div class="quote-item">
          <div class="quote-text">“${text}”</div>
          <div class="quote-source">
            <span>— ${author.name}${src ? ', ' + src : ''}</span>
            <span class="quote-lang">${langLabel}</span>
          </div>
        </div>
      `;
    }).join('');
  }

  function renderAuthorPage() {
    const author = getAuthorFromUrl();
    if (!author) {
      document.getElementById('quoteList').innerHTML =
        `<p>${t('authorNotFound')} <a href="index.html">${t('home')}</a></p>`;
      return;
    }
    document.title = author.name + ' · Quotes';
    $('#authorName').textContent = author.name;
    $('#backLink').textContent = t('back');
    ensureQuotesLoaded(author.id, () => {
      renderQuotes(author, window.QUOTES[author.id] || []);
    });
  }

  // ---------- REFRESH ----------
  function refresh() {
    setupLangBar();
    renderNav();
    const page = document.body.dataset.page;
    if (page === 'home') renderHome();
    else if (page === 'author') renderAuthorPage();
  }

  // ---------- INIT ----------
  document.addEventListener('DOMContentLoaded', () => {
    bindLangBar();
    refresh();
  });
})();

